version: '3'
services: 
  browser:
    container_name: links
    build: ./app/
    restart: always
    ports:
      - "2022:22"
    healthcheck:
      test: ["CMD", "socat", "TCP4:localhost:22", "-"]
      interval: 57s
      timeout: 3s
      retries: 1
  webpage:
    container_name: webpage
    build:
      context: ./web/
      args:
      - FLAG=${FLAG}
      - TASK_NAME=${TASK_NAME}
    ports:
      - "8014:8017"
    environment:
      - FLAG=${FLAG}
      - PORT=8017
      - IP=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8017"]
      interval: 1m30s
      timeout: 10s
      retries: 1
      start_period: 40s