apiVersion: v1
kind: Pod
metadata:
  name: old-tricks
spec:
  containers:
    - name: links
      image: mctf-old-tricks-ssh:latest
      ports:
        - containerPort: 22
      readinessProbe:
        tcpSocket:
          port: 22
        initialDelaySeconds: 57
        periodSeconds: 57
        timeoutSeconds: 3
        failureThreshold: 1
      resources:
        limits:
          cpu: 250m
          memory: 50Mi
        requests:
          cpu: 250m
          memory: 20Mi
    - name: redis
      image: redis:alpine
      resources:
        limits:
          cpu: 250m
          memory: 50Mi
        requests:
          cpu: 250m
          memory: 20Mi
    - name: webpage
      image: mctf-old-tricks-web:latest
      ports:
        - containerPort: 8017
      env:
        - name: FLAG
          value: "Br@US3rS_ar3_n0T-3n0uGH"
        - name: PORT
          value: "8017"
        - name: IP
          value: "0.0.0.0"
      readinessProbe:
        httpGet:
          path: /
          port: 8017
        initialDelaySeconds: 40
        periodSeconds: 90
        timeoutSeconds: 10
        failureThreshold: 3
